### ISSUE TITLE
Error while sending soft reset command, retrying...

### ISSUE THREAD

**Issue by Brahisam** [Sensirion/arduino-liquid-flow-snippets#2] opened 2019-07-26 10:08 UTC
Hi sir,
i copied the same code as you but i don't know why it's not working. I'm new to programming:/..

Thank you in advance.

![image](https://user-images.githubusercontent.com/53334916/61939743-3b836c00-af94-11e9-9a9d-68c19be72c67.png)
![image](https://user-images.githubusercontent.com/53334916/61944432-ef3d2980-af9d-11e9-95f9-da93a14f0dcb.png)

**Comment by abrauchli** [comment] 2019-07-26 12:05
Dear @Brahisam I forwarded your request to our support (support@sensirion.com). They thought that you might be running the wrong code. They recommend to use the LD20 code and adapt a few variables for the SLF3S:

![image](https://user-images.githubusercontent.com/216562/61950414-097f0380-afae-11e9-8068-cc648519a4a4.png)

They also strongly recommend to use pull up resistors with such long cables.

I hope this will help you.
Kindly note that since this is not a bug with the code, we can't provide further support through this channel. I am thus closing the issue. Feel free to reopen an issue, should you encounter a software related bug.

**Closed as completed by abrauchli** 2019-07-26 12:05 UTC

**Comment by c7h** [comment] 2019-07-31 09:49
The soft reset command for the SLF3S is `0x0006` if you can trust the datasheet.

**Comment by abrauchli** [comment] 2019-08-12 15:06
Thanks @c7h indeed, this is the general-call soft reset from the i2c spec. It works on all our sensors when sent to the general call address `0x00` - so if there are other devices on the bus they too should reset.

**Comment by abrauchli** [comment] 2019-08-12 15:08
Like you mentioned, documentation is the datasheet http://www.sensirion.com/file/datasheet_slf3x on p12
